### ISSUE TITLE
Dublication of papaer

### ISSUE THREAD

**Issue by DeepeshKalura** [gehuhaldwani/pyqs#2]
I observe in Btech 3 year 6 sem in Computer Network 1. 

has only 2023 and 2022 example papers. It has had the same questions since we need more different types of question because I study from PYQ only. If same question are repeated it increase the chance of failing in the exam.

I would like more questions added. So, my junior does not go through my pain. That looking more pyq just 5 hours before the exam.

**Comment by MG-LSJ** [comment]
This is a student contributed and managed repository. If you can help us find more pyqs then we would be grateful.
